core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.views import LogoutView
from core.views import (
    PostListView,
    NewsList,
    NewsDetail,
    NewsCreate,
    NewsUpdate,
    NewsDelete,
    LoginUser,
    RegisterView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    delete_user,
    delete_user_confirm,
    profile,
    post_like,
    delete_comment
)

app_name = 'core'

urlpatterns = [
    path('home_page/', NewsList.as_view(), name='home_page'),
    path('news_detail/<int:pk>', NewsDetail.as_view(), name='news_detail'),
    path('news_create/', NewsCreate.as_view(), name='news_create'),
    path('news_update/<int:pk>', NewsUpdate.as_view(), name='news_update'),
    path('news_delete/<int:pk>', NewsDelete.as_view(), name='news_delete'),
    path('posts/', PostListView.as_view(), name='posts'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:home_page'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('delete_user/', delete_user, name='delete_user'),
    path('delete_user/confirm/', delete_user_confirm, name='delete_confirm'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post_update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('profile/', profile, name='profile'),
    path('post_like/', post_like, name='post_like'),
    path('comment/<int:id>', delete_comment, name='delete_comment'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wingman/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('core.urls', namespace='core')),
                  path('', include('django.contrib.auth.urls')),
              ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from phone_field import PhoneField
from PIL import Image


# Create your models here.

class Section(models.Model):
    topic = models.CharField(max_length=255)

    def __str__(self):
        return self.topic


class Authors(models.Model):
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    job_title = models.CharField(max_length=255, blank=True)
    mail_address = models.EmailField(max_length=255, unique=True, blank=True)
    tel_num = PhoneField(null=False, blank=True, unique=True)
    birth_day = models.DateField(blank=True)
    portrait = models.ImageField(upload_to="authors_images/", null=True, blank=True)
    inf_about = models.TextField(max_length=2550, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)


class News(models.Model):
    title = models.CharField(max_length=255, blank=True)
    topic = models.ManyToManyField(Section)
    summary = models.TextField(max_length=25500, blank=True)
    picture = models.ImageField(upload_to="news_images/", null=True, blank=True)
    auth_opinion = models.TextField(max_length=2550, null=True)
    authors = models.ForeignKey('Authors', on_delete=models.SET_NULL, null=True)
    source = models.URLField(null=True)
    d_created = models.DateTimeField(blank=True, auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return '%s, %s' % (self.title, self.authors)


class Post(models.Model):
    title = models.CharField(max_length=255)
    topic = models.ManyToManyField(Section)
    caption = models.TextField(max_length=25500, blank=True)
    image = models.ImageField(upload_to="post_images/")
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    date_posted = models.DateTimeField(blank=True, auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    USERNAME_FIELD = 'username'

    def __str__(self):
        return f'{self.author.username}\'s Post- {self.title}'

    def like_count(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 400 or img.width > 400:
            # output_size = (300, 300)
            # img.thumbnail(output_size)
            im = img.resize((400, 400))
            im.save(self.image.path)
        elif img.height < 400 or img.width < 400:
            im = img.resize((400, 400))
            im.save(self.image.path)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(default="de_fault.png", upload_to="profiles")

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_image.path)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Комментарий к посту {} от пользователя {}'.format(self.post.title, self.user.username)


#
#        # resize the image
#        img = Image.open(self.avatar.path)
#        if img.height > 300 or img.width > 300:
#            output_size = (300, 300)
#            # create a thumbnail
#            img.thumbnail(output_size)
#            # overwrite the larger image
#            img.save(self.avatar.path)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from core.models import News, Section, Authors, Post, Profile
from django.contrib.auth.models import User


class NewsForm(ModelForm):
    title = forms.CharField(label="Название новости", required=True)
    topic = forms.ModelMultipleChoiceField(label="Раздел(ы) новости", queryset=Section.objects.all())
    summary = forms.CharField(widget=forms.Textarea, label="Содержание новости", required=True)
    picture = forms.FileField(label="Картинка для новости", required=False)
    auth_opinion = forms.CharField(widget=forms.Textarea, label="Мнение автора новости", required=False)
    authors = forms.ModelChoiceField(label="Автор новости", queryset=Authors.objects.all())
    source = forms.URLField(label="Источник новости", required=False)
    active = forms.BooleanField(label="Активна ли новость?")

    def clean_title(self):
        name = self.cleaned_data['title']
        if name.isdigit():
            raise forms.ValidationError('Название не должно являться числом!')
        return name

    class Meta:
        model = News
        fields = "__all__"


class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=255)
    username = forms.CharField(label="Никнейм на сайте")
    first_name = forms.CharField(label="Имя пользователя (нигде не используется)")

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password1', 'password2',)


class DiscussionForm(UserCreationForm):
    title = forms.CharField(label="Название обсуждения")
    topic = forms.ModelMultipleChoiceField(label="Раздел(ы) обсуждения", queryset=Section.objects.all())
    caption = forms.CharField(widget=forms.Textarea, label="Содержание новости", required=True)
    image = forms.FileField(label="Картинка для обсуждения", required=False)

    class Meta:
        model = Post
        fields = ['title', 'topic', 'caption', 'image']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=255)
    username = forms.CharField(label="Никнейм на сайте")
    first_name = forms.CharField(label="Имя пользователя (нигде не используется)")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    profile_image = forms.FileField(label="Изображение профиля", required=False)

    class Meta:
        model = Profile
        fields = ['profile_image']

core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import login
from django.views.generic.edit import FormView
from core.forms import RegisterForm, NewsForm, DiscussionForm, UserUpdateForm, ProfileUpdateForm
from core.models import Post, News, Comment


# Create your views here.
class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.get_title()
        return context


class NewsList(TitleMixin, ListView):
    model = News
    template_name = 'core/home_page.html'
    context_object_name = 'news'
    title = 'Wingman'


class NewsDetail(TitleMixin, DetailView):
    model = News
    template_name = 'core/news_detail.html'
    context_object_name = 'news_detail'
    title = "Новость"


class NewsCreate(TitleMixin, LoginRequiredMixin, CreateView):
    model = News
    template_name = 'core/news_create.html'
    context_object_name = 'news_create'
    form_class = NewsForm
    success_url = reverse_lazy('core:home_page')
    title = "Добавление новости"


class NewsUpdate(TitleMixin, LoginRequiredMixin, UpdateView):
    model = News
    template_name = 'core/news_update.html'
    context_object_name = 'news_update'
    form_class = NewsForm
    success_url = reverse_lazy('core:home_page')
    title = "Редактирование новости"


#    def form_valid(self, form):
#        messages.success(self.request, "Новость была обновлена успешно")
#        return super(NewsUpdate, self).form_valid(form)

#    def get_queryset(self):
#        base_qs = super(NewsUpdate, self).get_queryset()
#        return base_qs.filter(superuser=self.request.superuser)


class NewsDelete(TitleMixin, LoginRequiredMixin, DeleteView):
    model = News
    template_name = 'core/news_delete.html'
    context_object_name = 'news_delete'
    success_url = reverse_lazy('core:home_page')
    title = "Удаление новости"


#    def form_valid(self, form):
#        messages.success(self.request, "Новость была удалена успешно")
#        return super(NewsDelete, self).form_valid(form)

#    def get_queryset(self):
#        base_qs = super(NewsDelete, self).get_queryset()
#        return base_qs.filter(user=self.request.user)


class PostListView(TitleMixin, LoginRequiredMixin, ListView):
    model = Post
    template_name = 'core/posts.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    title = 'Обсуждения'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count'] = self.get_queryset().count()
        return context


class PostCreateView(TitleMixin, LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'topic', 'caption', 'image']
    success_url = reverse_lazy('core:posts')
    title = "Добавление обсуждения"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(TitleMixin, LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'core/post_update.html'
    context_object_name = 'post_update'
    form_class = DiscussionForm
    success_url = reverse_lazy('core:posts')
    title = "Обновление обсуждения"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def only_author(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(TitleMixin, LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'core/post_delete.html'
    context_object_name = 'post_delete'
    success_url = reverse_lazy('core:posts')
    title = "Удаление обсуждения"

    def only_author(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


@login_required
def post_like(request):
    if request.method == 'POST':
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        is_liked = False
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            is_liked = False
        else:
            post.likes.add(request.user)
            is_liked = True

        return HttpResponseRedirect(post.get_absolute_url())


@login_required
def delete_comment(request, id):
    comment = get_object_or_404(Comment, id=id)
    comment.delete()
    messages.success(request, f'Комментарий удалён!')
    return redirect(comment.post.get_absolute_url())


class LoginUser(TitleMixin, LoginView):
    redirect_authenticated_user = True
    template_name = 'core/login.html'
    context_object_name = 'login'
    title = 'Авторизация'

    def get_success_url(self):
        return reverse_lazy('core:home_page')

    def form_invalid(self, form):
        messages.error(self.request, 'Неверное имя пользователя или пароль')
        return self.render_to_response(self.get_context_data(form=form))


@login_required
def delete_user(request):
    context = {'title': 'Удаление аккаунта'}
    return render(request, 'core/delete_user.html', context)


@login_required
def delete_user_confirm(request):
    context = {}
    if request.user.is_authenticated:
        username = request.user.username
    try:
        u = User.objects.get(username=username)
        u.delete()
        context['msg'] = 'Аккаунт удалён'
    except User.DoesNotExist:
        context['msg'] = 'Аккаунта не существует'
    except Exception as e:
        context['msg'] = e.message

    messages.success(request, f' {username} account is deleted !')
    return redirect('core:home_page')


class RegisterView(TitleMixin, FormView):
    redirect_authenticated_user = True
    template_name = 'core/register.html'
    form_class = RegisterForm
    context_object_name = 'register'
    success_url = reverse_lazy('core:home_page')
    title = 'Регистрация'

    def form_valid(self, form):
        user = form.save()
        if user:
            login(self.request, user)
        return super(RegisterView, self).form_valid(form)


@login_required
def profile(request):
    if request.method == 'POST':
        uform = UserUpdateForm(request.POST, instance=request.user)
        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if uform.is_valid() and pform.is_valid():
            uform.save()
            pform.save()
    else:
        uform = UserUpdateForm(instance=request.user)
        pform = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'uform': uform,
        'pform': pform,
        'title': 'Обновить профиль'}
    return render(request, 'core/profile.html', context)

#    def form_valid(self, form):
#        messages.success(self.request, "Обсуждение было удалено успешно")
#        return super(DiscussionDelete, self).form_valid(form)

#    def get_queryset(self):
#        base_qs = super(DiscussionDelete, self).get_queryset()
#        return base_qs.filter(superuser=self.request.superuser)

core/templates/core/delete_user.html
{% extends "base.html" %}
{% block content %}

      <article class="media content-section row">
      	<div>
      		<p>
      			Hey {{ user.first_name|capfirst }}, Had a nice time !
      		</p>
             <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'core:posts'  %}">Changed your mind!</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'core:delete_confirm' %}">Are you sure want to delete your account?</a>
                </div>
      </article>
{% endblock content %}

core/templates/core/login.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Авторизация</title>
  </head>
  <body>
  <div class="container">
      {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
      {% endif %}
  </div>
  <form action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Имя пользователя</label>
        <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
      </div>
      <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Пароль</label>
        <input type="password" class="form-control" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Войти</button>
  </form>
  </body>
</html>

core/templates/core/news_create.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{title}}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>
    <body>
        <form action="{% url 'core:news_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Добавить</button>
        </form>
    </body>
</html>

core/templates/core/news_delete.html
<!doctype html>
<html lang="en">
   <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>{{title}}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            <p>Вы уверены, что хотите удалить "{{ object }}"?</p>
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger" value="Confirm">Удалить</button>
            <a class="btn btn-success" href="{% url 'core:home_page' %}"  role="button">Отмена</a>
        </form>
    </body>
</html>

core/templates/core/news_detail.html
<!doctype html>
<html lang="en">
   <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>{{title}}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   </head>
    <body>
        <style>
             body { background: #E0FFFF }
             button { background: #AFEEEE }
         </style>
        <h1>{{news.title}}</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </body>
</html>

core/templates/core/news_update.html
<!doctype html>
<html lang="en">
   <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>{{title}}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value="Update">Изменить</button>
        </form>
    </body>
</html>

core/templates/core/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Удаление обсуждения</legend>
                <h2>Вы уверены, что хотите удалить обсуждение: "{{ object.title|capfirst  }}" ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Да, удалить</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Отмена</a>
            </div>
        </form>
    </div>
{% endblock content %}

core/templates/core/post_create.html
{% extends 'base.html' %}
{% block content %}
        <form action="{% url 'core:post_create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Добавить</button>
        </form>
{% endblock %}

core/templates/core/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="jumbo-tron">
  <h1 class="display-4">Create a New Post!!</h1>
  <hr class="my-4">
  <p><i>Its time to rock</i></p>
</div>
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group" >
                <legend class="border-bottom mb-4">Socio Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

core/templates/core/post_update.html
{% extends 'base.html' %}
{% block content %}
   <head>
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>{{title}}</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
   </head>
    <body>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value="Update">Изменить</button>
        </form>
    </body>
{% endblock %}

core/templates/core/posts.html
{% extends "base.html" %}
{% block content %}
<style>
   hr {
    border: none;
    background-color: black;
    color: black;
    height: 2px;
   }
</style>

<div class="topbar">
    <h1>Список обсуждений</h1>
</div>

<p align="left">Кол-во обсуждений: {{ count }}</p>
<hr>
{% for post in posts %}
<article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <p><strong>Автор обсуждения: {{ post.author }}</strong></p>
              <p><strong>Название: {{ post.title  }}</strong></p>
            </div>
            <p class="article-content">
              <small class="text-muted">Дата создания: {{ post.date_posted|date:"F d, Y" }}</small>
            </p>
            <p class="article-content">Понравилось: {{ post.like_count }}  <i class="fa fa-heart fa-lg" style="color: red;" aria-hidden="true"></i></p>
          </div>
</article>
{% endfor %}
{% endblock content %}

core/templates/core/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Профиль пользователя</h1>
    <hr>
        <div class="content-section">
          <div class="media">
            <img class="rounded-circle imgg"  src="{{ user.profile.profile_image.url }}">
            <div class="media-body">
              <h2 class="imgh">Имя пользователя: {{ user.username }}</h2>
              <h2 class="imgh">Почтовый адрес пользователя: {{ user.email }}</h2>
            </div>
          </div>
          <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Информация о профиле</legend>
                    {{ uform|crispy }}
                    {{ pform|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Обновить</button>
                </div>
            </form>
        </div>
<br><br><br><br><br><br>
{% endblock %}

core/templates/core/register.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Регистрация</title>
  </head>
  <body>
	<div class="center">
	  <form method="post" novaldiate class="card">
	  	{% csrf_token %}
	    <h2 class="text-center">Создайте свой аккаунт</h2>
		{% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
	        	{% if field.errors %}
	        		<small class="error">{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}

		<input type="submit" value="Зарегистрироваться" class="btn btn-primary full-width">
		<hr>
		<p class="text-center">Уже зарегистрированы?<a href="{% url 'core:login'%}">Войти здесь</a></p>
		</form>
	</div>
  </body>
</html>